### ISSUE TITLE
NPE can be thrown if mime type aren't registered

### ISSUE THREAD

**Issue by volyx** [pawandubey/griffin#44]
```
Exception in thread "main" java.lang.NullPointerException
        at com.pawandubey.griffin.DirectoryCrawler$1.visitFile(DirectoryCrawler.java:110)
        at com.pawandubey.griffin.DirectoryCrawler$1.visitFile(DirectoryCrawler.java:90)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2803)
```

https://github.com/pawandubey/griffin/blob/b44e64038973c458e7aa71c9fb1a5d7a0fe2fd99/src/main/java/com/pawandubey/griffin/DirectoryCrawler.java#L110

**Comment by volyx** [comment]
Duplicate of https://github.com/pawandubey/griffin/issues/38

**Comment by pawandubey** [comment]
Thanks for the report. This has been a constant source of frustration. I've borrowed the fix from your fork and given you a co-author credit. Hope you don't mind.
